config/routes.rb
Rails.application.routes.draw do
    
  resources :contacts, only: [:index, :create, :destroy] do
    resources :messages, only: [:index, :create, :update, :destroy]
    get '/messages_history', to: 'messages#history', as: "messages_history"
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'contacts#index'

  mount ActionCable.server => '/cable'

  match '*a', to: 'errors#routing', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  acts_as_paranoid
  
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :content, presence: true

  scope :not_read, ->{ where(is_read: false) }
  scope :to_user, ->(user_id){ where(to_user_id: user_id) }

  after_create_commit :sync_update_message, :sync_update_contacts_list
  after_destroy_commit :sync_clear_contact_message, :sync_update_unread_badge

  private

  # 新的消息创建后发布到对应联系人channel，双方一起更新聊天消息
  # 不会 coffee 的语法，目前只能很笨的在后台拼接 html，将两种显示方式一起发送，前端判断是否是发送者再选择渲染
  def sync_update_message
    UpdateMessageJob.perform_later self
  end

  # 发送消息时更新对方联系人列表的对应未读消息数
  # 如果消息发送者不是接受者的联系人，则自动更新接受者的联系人列表
  def sync_update_contacts_list
    UpdateContactsListJob.perform_later self
  end

  # ISSUE: perform_later ?
  # 删除自己消息的同时将对方联系人聊天框中的相应消息清除
  def sync_clear_contact_message
    ClearContactMessageJob.perform_now self
  end

  # 删除信息时，同步更新联系人列表页面的未读消息
  def sync_update_unread_badge
    UpdateUnreadBadgeJob.perform_now self
  end

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login
  acts_as_paranoid
  has_many :messages
  has_many :contacts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  # issue: 需要考虑username的大小写问题，方便起见我没有hack devise controller所以用了成本最低的方式，只允许username用
  # 小写注册，否则由于登录时忽略大小写会造成username混乱
  validates :username, presence: true, uniqueness: true, length: { in: 6..20 }
  validates_format_of :username, with: /^[a-z0-9_\.]*$/, :multiline => true


  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def add_contact(contact_params)
    # 判断是否存在这个联系人账户
    if contact_params.include? '@'
      contact_user = User.find_by(email: contact_params.downcase)
      unless contact_user
        return { status: "not_found" }
      end
      contact_user_id = contact_user.id
    elsif contact_params.length > 5
      contact_user = User.find_by(username: contact_params)
      unless contact_user
        return { status: "not_found" }
      end
      contact_user_id = contact_user.id
    else
      return { status: "not_found" }
    end
    # 判断是否是历史联系人
    contacts_deleted = self.contacts.only_deleted
    if contacts_deleted && contacts_deleted.map(&:contact_id).include?(contact_user_id)
      d_contact = Contact.only_deleted.find_by(user_id: self.id, contact_id: contact_user_id)
      # issue: 这里还要处理一个逻辑，将 updated_at 置为 now，联系人的添加时间要现实 updated_at
      Contact.restore(d_contact.id)
      return {
        status: "old",
        contact_user_id: contact_user_id
        }
    # 判断是否已经添加到联系人
    elsif self.contacts.map(&:contact_id).include?(contact_user_id)
      return { status: "taken" }
    else
      @contact = self.contacts.new(contact_id: contact_user_id)
      @contact.save
      {
        status: "success",
        contact_user_id: contact_user_id
      }
    end
  end

  # 获取当前用户与联系人聊天记录
  def get_all_messages(contact_user, count=nil)
    self_messages = self.messages.to_user(contact_user.id)
    cont_messages = contact_user.messages.to_user(self.id)
    if count
      self_messages = self_messages.last(count)
      cont_messages = cont_messages.last(count)
    end
    messages_array = []
    self_messages.each {|m| messages_array << m if m}
    cont_messages.each {|m| messages_array << m if m}
    # 将 array 转换成 relation 用于时间排序
    messages_ids = messages_array.map(&:id)
    all_messages = Message.includes(:user).where(id: messages_ids).order(:created_at)
    count ? all_messages.last(count) : all_messages
  end

  # 将联系人用户未读消息置否
  def clear_messages_unread_count(current_user_id)
    self.messages.to_user(current_user_id).not_read.update_all(is_read: true)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # 重定向登录后的页面。暂且用不到
  # def after_sign_in_path_for(resource)
  #   user_contacts_path
  # end

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: :destroy

  def index
    contact_ids = current_user.contacts.map(&:contact_id)
    @contact_users = User.find(contact_ids)
  end

  def create
    result = current_user.add_contact(contact_params[:contact_id])
    if result[:status] == "old" || result[:status] == "success"
      @new_contact = User.find(result[:contact_user_id])
    end
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def set_contact
    @contact = Contact.find_by(user_id: current_user.id, contact_id: params[:id])
  end

  def contact_params
    params.require(:contact).permit(:contact_id)
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def routing
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_contact_user, only: [:index, :create, :history]
  before_action :set_message, only: [:destroy, :update]

  def index
    # 聊天框初始只显示最后 5 次记录
    @messages = current_user.get_all_messages(@contact_user, 5)
    # 进入聊天后，将此联系人用户未读消息置否
    @contact_user.clear_messages_unread_count(current_user.id)
    
    @message = current_user.messages.new
  end

  def history
    @messages = current_user.get_all_messages(@contact_user)
  end

  def create
    @message = current_user.messages.build(message_params)
    @message.update_attributes(to_user_id: params[:contact_id])
    respond_to do |format|
      if @message.save
        # 保存成功的话，就执行 after_create_commit，不返回任何内容，交由actioncable处理
        format.js { head :no_content }
      else
        # TODO: 消息为空时的处理有点丑，暂且如此，先去处理别的优先级高的功能
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      @message.update(is_read: true)
      format.js { head :no_content }
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      # 页面的消息清除动作交给 actioncable 执行
      format.js { head :no_content }
    end
  end

  private
  
  def set_contact_user
    @contact_user = User.find(params[:contact_id])
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def not_read_messages_count(user)
    user.messages.to_user(current_user.id).not_read.count
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/contacts/_contact.html.slim
tr id="contact_user_#{contact.id}"
  td = contact.id
  td = contact.username
  td = contact.email
  td = contact.updated_at
  td = link_to contact_messages_path(contact), class: "btn btn-success" do
    = fa_icon "comments", class: "fa-fw"
    '
    | 聊天
    '
    |
    - if not_read_messages_count(contact) == 0
      span.badge id="badge_#{contact.id}"
        = not_read_messages_count(contact)
    - else
      span.badge id="badge_#{contact.id}" style="color:red"
        = not_read_messages_count(contact)
  td = link_to contact_path(contact), remote: true, method: :delete, class: "btn btn-danger", data: { confirm: '确认删除？' } do
    = fa_icon "user-times", class: "fa-fw"
    '
    | 删除联系人

app/views/contacts/_modal.html.slim
.modal.fade id="new_contact_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  .modal-dialog
    .modal-content
      .modal-header
        h3.modal-title 添加联系人
      .modal-body
        = simple_form_for :contact, url: contacts_path, remote: true, method: :post do |f|
          .form-inputs
            = f.input :contact_id, label: false, placeholder: '请输入 邮箱 / 用户名 添加联系人', required: true, autofocus: true
          hr
          .form-actions
            = button_tag(type: :submit, class: "btn btn-primary btn-block") do
              = fa_icon "user-plus", class: "fa-fw"
              '
              | 添 加
            = link_to "#", class: "btn btn-warning btn-block", data: { dismiss: "modal" } do
              = fa_icon "chevron-circle-left", class: "fa-fw"
              '
              | 返 回 
        end

app/views/contacts/_newContact.html.slim
tr id="contact_user_#{contact.id}"
  td = contact.id
  td = contact.username
  td = contact.email
  td = contact.updated_at
  td = link_to contact_messages_path(contact), class: "btn btn-success" do
    = fa_icon "comments", class: "fa-fw"
    '
    | 聊天
    '
    |
    / 原本这里利用 not_read_messages_count(contact) helper 方法计算未读数，但是在 model 无法获取 devise 的 current_user，所以当被动同步新增联系人的时候，在后台计算好未读数再渲染这个新的newContact模版
    span.badge id="badge_#{contact.id}" style="color:red"
      = count
  td = link_to contact_path(contact), remote: true, method: :delete, class: "btn btn-danger", data: { confirm: '确认删除？' } do
    = fa_icon "user-times", class: "fa-fw"
    '
    | 删除联系人

app/views/contacts/create.js.erb
<% if @new_contact %>
  $('#new_contact_modal').modal('hide');
  $('#contacts_list').append("<%= j render(partial: 'contact', locals: { contact: @new_contact }) %>");
<% else %>
// TOTO： 增加更友好的错误提示
  alert("输入有误！添加失败。");
<% end %>

app/views/contacts/destroy.js.erb
$('#contact_user_<%= params[:id] %>').remove();

app/views/contacts/index.html.slim
table.table.table-striped.table-hover
  thead
    tr
      th 联系人编号
      th 联系人用户名
      th 联系人邮箱
      th 添加时间
      th 聊天／未读消息

  tbody id="contacts_list" data-current-user-id="#{current_user.id}"
    - @contact_users.each do |contact_user|
      = render partial: 'contact', locals: { contact: contact_user }
= link_to "#", class: "btn btn-primary", data: { toggle: "modal", target: "#new_contact_modal" } do
  = fa_icon "user-plus", class: "fa-fw"
  '
  | 新建联系人

= render 'modal'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebMessage</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title WebMessage
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
  
  body
    nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          .navbar-brand WebMessage by Aaron Zhang
        
        .nav.navbar-nav.navbar-right
          - if user_signed_in?
            .dropdown.navbar-brand
              a.dropdown-toggle data-toggle="dropdown" href="#"
                '
                | Welcome,
                '
                |
                = current_user.username
                ' 
                span.caret
              ul.dropdown-menu.dropdown-menu-left
                li
                  = link_to edit_user_registration_path do
                    = fa_icon "gear", class: "fa-fw"
                    '
                    | 更改资料
                li
                  = link_to contacts_path do
                    = fa_icon "users", class: "fa-fw"
                    '
                    | 前往联系人列表
                li.divider
                li
                  = link_to destroy_user_session_path, method: :delete do
                    = fa_icon "sign-out", class: "fa-fw"
                    '
                    | 注 销
                  end

    - if notice
      .notice.alert.alert-success
        = notice
        a.close type="button" data-dismiss="alert" &times;
    - if alert
      .alert.alert-danger
        = alert
        a.close type="button" data-dismiss="alert" &times;
        
    .container-fluid
      .row
        .col-lg-12.col-xs-12.col-sm-12
          .panel.panel-default
            .panel-body
              = yield

app/views/messages/_message.html.slim
/ - if m.user.id == current_user.id
.panel.panel-info id="message_#{m.id}"
  .panel-body.text-right
    small = m.created_at
    br
    span style="color: #003366;"
      = m.content
      '
      |
      = link_to contact_message_path(m.to_user_id, m), remote: true, method: :delete do
        = fa_icon "times-circle", class: "fa-fw"
/ - else
/   .panel.panel-default
/     .panel-body
/       small = m.created_at
/       br
/       = m.content

app/views/messages/_messageMy.html.slim
/ 原来是在前端判断消息输出格式，后来用了 actioncable 实现 websocket 实时接收功能，因为不熟悉 coffee 语法，所以放到了后台直接把消息包成 html 再传到前端，这样 coffee 就只用判断用哪个模版了
/ - if m.user.id == current_user.id
.panel.panel-info id="message_#{m.id}"
  .panel-body.text-right
    small 
      = m.user.username
      '
      | |
      '
      |
      = m.created_at
    br
    span style="color: #003366;"
      = m.content
      '
      |
      = link_to contact_message_path(m.to_user_id, m), remote: true, method: :delete do
        = fa_icon "times-circle", class: "fa-fw"
/ - else
/   .panel.panel-default
/     .panel-body
/       small = m.created_at
/       br
/       = m.content

app/views/messages/_messageYou.html.slim
.panel.panel-default id="message_#{m.id}"
  .panel-body
    small
      = m.user.username
      '
      | |
      '
      |
      = m.created_at
    br
    = m.content

app/views/messages/_messages.html.slim
/ 因为历史消息过多，这里直接把'message'代码贴过来循环输出，否则会造成大量的 render partial
- messages.each do |m|
  - if m.user.id == current_user.id
    .panel.panel-info id="message_#{m.id}"
      .panel-body.text-right
        small 
          = m.user.username
          '
          | |
          '
          |
          = m.created_at
        br
        span style="color: #003366;"
          = m.content
          '
          |
          = link_to contact_message_path(m.to_user_id, m), remote: true, method: :delete do
            = fa_icon "times-circle", class: "fa-fw"
  - else
    .panel.panel-default id="message_#{m.id}"
      .panel-body
        small
          = m.user.username
          '
          | |
          '
          |
          = m.created_at
        br
        = m.content

app/views/messages/create.js.erb
<% if @message.id %>
  // $('#message-box').append("<%= j render(partial: 'message', locals: { m: @message }) %>");
  // $('#message-box').scrollTop($('#message-box').height());
  // $('#message_content').val("");
<% else %>
// TOTO： 增加更友好的错误提示
  alert("消息不可为空！");
<% end %>

app/views/messages/history.html.slim
.container-fluid
  .row
    .col-lg-12.col-xs-12.col-sm-12
      .panel.panel-info
        .panel-heading
          h3.panel-title
            = fa_icon "user", class: "fa-fw"
            '
            |
            = @contact_user.username
            '
            | -
            '
            | 历史消息
        h4.panel-body id="message-box" style="height: 450px; overflow-y: scroll;"
          = render partial: 'messages', locals: { messages: @messages }
        .panel-footer
          = link_to contact_messages_path(@contact_user), class: "btn btn-warning" do
            = fa_icon "chevron-circle-left", class: "fa-fw"
            '
            | 返 回       

javascript:
  var mbox = document.getElementById('message-box');
  mbox.scrollTop = mbox.scrollHeight;

app/views/messages/index.html.slim
.container-fluid
  .row
    .col-lg-12.col-xs-12.col-sm-12
      .panel.panel-primary
        .panel-heading
          h3.panel-title
            = fa_icon "user", class: "fa-fw"
            '
            |
            = @contact_user.username
            '
            | -
            '
            | 在线聊天
        h4.panel-body id="message-box" data-current-user-id="#{current_user.id}" data-contact-user-id="#{@contact_user.id}" style="height: 400px; overflow-y: scroll;"
          = render partial: 'messages', locals: { messages: @messages }
  .row
    .col-lg-12.col-xs-12.col-sm-12
      = simple_form_for @message, url: contact_messages_path(@contact_user), remote: true, method: :post do |f|
        .form-inputs
          = f.input :content, label: false, placeholder: '输入要发送的消息', required: true, autofocus: true
        .form-actions
          = button_tag(type: :submit, class: "btn btn-success") do
            = fa_icon "send", class: "fa-fw"
            '
            | 发 送
          '
          |
          = link_to contacts_path, class: "btn btn-warning" do
            = fa_icon "chevron-circle-left", class: "fa-fw"
            '
            | 返 回 
          .pull-right
            = link_to contact_messages_history_path, class: "btn btn-info" do
              = fa_icon "history", class: "fa-fw"
              '
              | 历史消息
      end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>